# Generated by Django 4.0.3 on 2022-04-10 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegr_id', models.BigIntegerField(verbose_name="Telegram's ID")),
                ('user_name', models.CharField(max_length=255, null=True, verbose_name="User's name")),
                ('passw', models.CharField(max_length=255, null=True, verbose_name='Password')),
                ('subscription', models.DateTimeField(null=True, verbose_name='Subscription')),
                ('image', models.ImageField(default=None, null=True, upload_to='', verbose_name="Profile's photo")),
            ],
        ),
    ]
